### PR TITLE
Scroll To top button added

### PR DESCRIPTION
**Pull request by AdarshP1133**

### CODE REVIEW

**Comment by danishzayan** [comment]
@AdarshP1133 Arrow color should be green like message button and animated infinite time, circle 🔴 background white transparent circle border should be like card. Plz fix it after that I will merge your code.

**Comment by danishzayan** [comment]
You have done good work but https://github.com/danishzayan/StudentsShowcase/pull/5#issuecomment-1741713475 follow it

**Comment by AdarshP1133** [comment]
> @AdarshP1133 Arrow color should be green like message button and animated infinite time, circle 🔴 background white transparent circle border should be like card. Plz fix it after that I will merge your code.

Done!

**Comment by danishzayan** [comment]
> > @AdarshP1133 Arrow color should be green like message button and animated infinite time, circle 🔴 background white transparent circle border should be like card. Plz fix it after that I will merge your code.
> 
> Done!

@AdarshP1133 good job.. i like it..⚡

**Pull request merged**
